---
glob: "**/*.{html,text,js}{+*,}.{erb,md}"
exclude:
  - "**/.vscode/**/*"
  - "**/node_modules/**/*"
linters:
  ParserErrors:
    exclude:
      - "**/*.md"
  SpaceInHtmlTag:
    exclude:
      - "**/*.md"
  ErbSafety:
    enabled: true
    # better_html_config: .better-html.yml
    exclude:
      - "**/.vscode/**/*"
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
